In [1]:
import numpy as np

In [4]:
def sigmoid(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    else:
        return (1/1+(np.exp(-x)))

In [24]:
np.random.seed(3)

from statistics import mean
x=2*np.random.random((3,1))-1
print(x)
np.average(x)

[[ 0.10159581]
 [ 0.41629565]
 [-0.41819052]]


0.033233642737083104

In [40]:
X=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])

Y=np.array([[0],[0],[1],[1]])
print(X)
y=np.array([0,0,1,1]).T
np.shape(Y)
np.shape(y)
y

[list([0, 0, 1]) list([0, 1, 1]) list([1, 0, 1]) list([1, 1])]


array([0, 0, 1, 1])

In [18]:
np.random.seed(1)

In [48]:
syn0=np.random.random((3,4)).T
syn0.shape

(4, 3)

In [45]:
y = np.array([[0,0,1,1]]).T
y.shape

(4, 1)

In [52]:
import numpy as np

x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print(x,x.shape)

y=np.array([[0,0,1,1]]).T
print(y,y.shape)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]] (4, 3)
[[0]
 [0]
 [1]
 [1]] (4, 1)


In [50]:
#http://iamtrask.github.io/2015/07/12/basic-python-network/

def sigmoid(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    else:
        return 1/(1+np.exp(-x))

In [57]:
np.random.seed(1)
syn0=2*np.random.random((3,4))-1   #multiplying with 2 and minus 1 to get mean 0, and 3,4 shape to multiply with 4,3 x
print(syn0,np.average(syn0))

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]] -0.29154881789422876


In [58]:
syn1=2*np.random.random((4,1))-1  #shape(4,1) as it has to be multiplied with l1(4,4) and result in (4,1) output
print(syn1,np.average(syn1))

[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]] -0.10978760525060438


In [63]:
for i in range(10):
    l0=x
    l1=sigmoid(np.dot(l0,syn0))
    #l2=sigmoid(np.dot(l1,syn1))
    
    error=l1-y
    print(error)
    
    l1delta=error*sigmoid(l1,deriv=True)
    #print(l1delta)

[[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [-0.59204386 -0.37325394 -0.76158378 -0.50622364]
 [-0.74628752 -0.57371885 -0.85678767 -0.58267746]]
[[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [-0.59204386 -0.37325394 -0.76158378 -0.50622364]
 [-0.74628752 -0.57371885 -0.85678767 -0.58267746]]
[[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [-0.59204386 -0.37325394 -0.76158378 -0.50622364]
 [-0.74628752 -0.57371885 -0.85678767 -0.58267746]]
[[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [-0.59204386 -0.37325394 -0.76158378 -0.50622364]
 [-0.74628752 -0.57371885 -0.85678767 -0.58267746]]
[[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [-0.59204386 -0.37325394 -0.76158378 -0.50622364]
 [-0.74628752 -0.57371885 -

In [65]:
np.random.seed(1)

w0=2*(np.random.random((3,1)))-1
w0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [69]:


l0=x

l1=sigmoid(np.dot(l0,w0))

print(l1)
error=l1-y
print(error)

l1delta=error*sigmoid(l1,deriv=True)
print(l1delta)

w0+=np.dot(l1delta,)

[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
[[ 0.2689864 ]
 [ 0.36375058]
 [-0.76237183]
 [-0.6737243 ]]
[[ 0.05289153]
 [ 0.08418501]
 [-0.13811206]
 [-0.14809799]]


In [102]:
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print(x,x.shape)

y=np.array([[0,0,1,1]]).T
y

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]] (4, 3)


array([[0],
       [0],
       [1],
       [1]])

In [103]:
np.random.seed(1)

w0=2*np.random.random((3,1))-1
w0

array([[-0.16596],
       [ 0.44065],
       [-0.99977]])

In [104]:
def sigmoid(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    else:
        return 1/(1+np.exp(-x))

In [105]:
for i in range(10000):
    l0=x
    l1=sigmoid(np.dot(l0,w0))
    
    error=y-l1
    
    #print("Error is :",error)
    
    l1delta=error*sigmoid(l1,deriv=True)
    
    w0+=np.dot(l0.T,l1delta)

In [106]:
np.set_printoptions(precision=5,suppress=True)
print(l1,y)

[[0.00966]
 [0.00787]
 [0.99359]
 [0.99212]] [[0]
 [0]
 [1]
 [1]]
